import type { Campaign, Profile, Settings } from "./types";

export const seedProfile: Profile = {
  name: "Alex Moreau",
  company: "Kineet Demo SARL",
  phone: "+33 6 12 34 56 78",
  email: "alex@kineetdemo.fr",
  photo: "",
};

export const seedSettings: Settings = {
  emailNotifications: true,
  pushNotifications: false,
  campaignReports: true,
  darkMode: true,
  language: "Français",
  emailSignature: "Envoyé avec Kineet — Alex Moreau, Kineet Demo SARL",
};

export const seedCampaigns: Campaign[] = [
  {
    id: "cmp-1042",
    name: "Annonce soldes de printemps",
    channel: "whatsapp",
    status: "sent",
    recipients: 4820,
    delivered: 4773,
    failed: 47,
    message: "Bonjour {{prénom}}, nos soldes de printemps sont ouvertes avec jusqu'à 40 % de réduction !",
    createdAt: "2026-06-24T09:12:00.000Z",
  },
  {
    id: "cmp-1041",
    name: "Newsletter de juin",
    channel: "email",
    status: "sent",
    recipients: 12940,
    delivered: 12701,
    failed: 239,
    subject: "Votre actualité de juin — Kineet Demo SARL",
    message: "Bonjour {{prénom}}, voici toutes les nouveautés de ce mois.",
    createdAt: "2026-06-18T14:30:00.000Z",
  },
  {
    id: "cmp-1040",
    name: "Rappels de rendez-vous",
    channel: "sms",
    status: "sent",
    recipients: 860,
    delivered: 852,
    failed: 8,
    message: "Bonjour {{prénom}}, rappel de votre rendez-vous demain à 10 h.",
    createdAt: "2026-06-15T08:00:00.000Z",
  },
  {
    id: "cmp-1039",
    name: "Invitation webinaire",
    channel: "email",
    status: "sent",
    recipients: 3120,
    delivered: 3001,
    failed: 119,
    subject: "Vous êtes invité : scaler avec Kineet",
    message: "Bonjour {{prénom}}, rejoignez notre webinaire en direct ce jeudi.",
    createdAt: "2026-06-10T16:45:00.000Z",
  },
  {
    id: "cmp-1038",
    name: "Promotion flash",
    channel: "whatsapp",
    status: "failed",
    recipients: 540,
    delivered: 0,
    failed: 540,
    message: "Bonjour {{prénom}}, promotion flash 24 h à découvrir !",
    createdAt: "2026-06-05T11:20:00.000Z",
  },
  {
    id: "cmp-1037",
    name: "Lancement programme fidélité",
    channel: "sms",
    status: "sent",
    recipients: 2210,
    delivered: 2188,
    failed: 22,
    message: "Bonjour {{prénom}}, bienvenue dans notre nouveau programme fidélité !",
    createdAt: "2026-05-28T10:05:00.000Z",
  },
  {
    id: "cmp-1036",
    name: "Mise à jour produit",
    channel: "email",
    status: "sent",
    recipients: 9870,
    delivered: 9712,
    failed: 158,
    subject: "Les nouvelles fonctionnalités que vous allez adorer",
    message: "Bonjour {{prénom}}, découvrez les nouveautés de notre dernière version.",
    createdAt: "2026-05-20T13:15:00.000Z",
  },
  {
    id: "cmp-1035",
    name: "Demande de sondage",
    channel: "whatsapp",
    status: "sent",
    recipients: 1340,
    delivered: 1298,
    failed: 42,
    message: "Bonjour {{prénom}}, votre avis en 2 minutes nous intéresse.",
    createdAt: "2026-05-12T09:40:00.000Z",
  },
];

export const SAMPLE_FIRST_NAMES = ["Marie", "Jean", "Sofia", "Lucas", "Noah", "Emma"];
export const SAMPLE_LAST_NAMES = ["Garcia", "Martin", "Rossi", "Dubois", "Müller", "Chen"];
